CREATE TABLE DEPARTMENT (
    DEPT_NO varchar(10) NOT NULL,
    DEPT_NAME varchar(200) UNIQUE  NOT NULL,
    PRIMARY KEY (DEPT_NO)
    );

CREATE TABLE DEPT_EMP (
    EMP_NO int   NOT NULL,
    DEPT_NO varchar(10)   NOT NULL,
    PRIMARY KEY (EMP_NO,DEPT_NO)
);

CREATE TABLE DEPT_MANAGER (
    DEPT_NO varchar(10)   NOT NULL,
    EMP_NO int   NOT NULL,
    PRIMARY KEY (DEPT_NO,EMP_NO)
);

CREATE TABLE EMPLOYEE (
    EMP_NO int   NOT NULL,
    EMP_TITLE_ID varchar(10)   NOT NULL,
    BIRTH_DATE date   NOT NULL,
    FIRST_NAME varchar(200)   NOT NULL,
    LAST_NAME varchar(200)   NOT NULL,
    SEX varchar(1)   NOT NULL,
    HIRE_DATE date   NOT NULL,
    PRIMARY KEY (EMP_NO)
);

CREATE TABLE SALARY (
    EMP_NO int   NOT NULL,
    SALARY int   NOT NULL,
    PRIMARY KEY (EMP_NO)
);

CREATE TABLE TITLE (
    TITLE_ID varchar(10)   NOT NULL,
    TITLE varchar(200)   NOT NULL,
    PRIMARY KEY (TITLE_ID)
);

ALTER TABLE DEPT_EMP ADD FOREIGN KEY(EMP_NO)
REFERENCES EMPLOYEE (EMP_NO);

ALTER TABLE DEPT_EMP ADD FOREIGN KEY(DEPT_NO)
REFERENCES DEPARTMENT (DEPT_NO);

ALTER TABLE DEPT_MANAGER ADD FOREIGN KEY(DEPT_NO)
REFERENCES DEPARTMENT (DEPT_NO);

ALTER TABLE DEPT_MANAGER ADD FOREIGN KEY(EMP_NO)
REFERENCES EMPLOYEE (EMP_NO);

ALTER TABLE EMPLOYEE ADD FOREIGN KEY(EMP_TITLE_ID)
REFERENCES TITLE (TITLE_ID);

ALTER TABLE SALARY ADD FOREIGN KEY(EMP_NO)
REFERENCES EMPLOYEE (EMP_NO);
